name: aiida-user-addons

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    services:
      rabbitmq:
        image: rabbitmq:latest
        ports:
          - 5672:5672
    strategy:
      matrix:
        python: ['3.7', '3.8', '3.9']
    steps:
      - uses: actions/checkout@v2

      - name: Cache python dependencies
        id: cache-pip
        uses: actions/cache@v1
        with:
            path: ~/.cache/pip
            key: pip-${{ matrix.python }}-tests-${{ hashFiles('**/setup.json') }}
            restore-keys:
                pip-${{ matrix.python }}-tests-

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install postgresql
      - name: Upgrade pip
        run: |
          pip install --upgrade pip
          pip --version
      - name: Install wheel
        run: pip install wheel
      - name: Install AiiDA
        run: pip install 'aiida-core>=1.6.1,<2'
      - name: Install aiida-vasp
        run: pip install -e git+https://github.com/zhubonan/aiida-vasp@bz-changes#egg=aiida-vasp[tests]
      - name: Install package
        run: |
          pip install -e .
          reentry scan -r aiida
      - name: Record python dependencies
        run: pip freeze
      - name: Run pytest
        run: pytest aiida_user_addons
